package common

const (
	BEGIN_SEND_BETS = "BET"
	END_SEND_BETS = "END"
	GET_WINNERS = "WIN"
	BATCH_SENT_OK = "OK"
	BATCH_SENT_FAIL = "FAIL"
	WAIT_FOR_WINNERS_RESULT = "WAIT"
	WINNERS_RESULT = "WINNERS"
	BATCH_END_CHAR byte = '|'
	MAX_BATCH_SIZE = 8192
	READ_BUFFER_SIZE = 1024
)